### ISSUE TITLE
Feature reqest: make update-user-panel a separate view

### ISSUE THREAD

**Issue by macpli** [macpli/user-manager-ng#3]
#### Description
Update user  panel is currently poorly implemented inside a table cell for every user. When update button is pressed change into a new view containing update-user-panel.

#### Files
src/app/components/update-user
src/app/components/users-panel

#### Tasks
- [x] Create new view
- [x] Pass id, change routing 
- [x] Probably fix events 
- [x] Add return do users-panel & refresh
- [x] Unify style 
- [x] Done
